#!/usr/bin/env python
from __future__ import absolute_import, division, print_function, unicode_literals
import sys
import node


if len(sys.argv) != 1 + 4:
    print("deploy.py <app user> <app name> <source repo> <app_dir>")
    sys.exit(0)

app_user, app_name, source_repo, app_dir = sys.argv[1:]
deployer = node.GitDeploy(app_user, app_name, source_repo, app_dir)
deployer.deploy()
