#!/bin/sh

git_init() {
    stack=$1
    mkdir -p $stack
    $(cd $stack && git init && git remote add origin "git@github.com:stackful/$stack.git")
}

git_update() {
    dir=$1
    $(cd $dir && git pull origin master && git submodule update --init)
}

update_stack() {
    stack=$1
    echo "stack: $stack"

    # Prepare stack subfolder before provisioning
    if [ -d $stack ] ; then
        echo "Stack repo '$stack' already set up. Updating..."
        git_update $stack
    else
        git_init $stack
        git_update $stack
    fi
}

update_stack "stackful-node"
update_stack "stackful-python"

vagrant up
